name: App build

permissions:
  contents: write

on:
  push:

jobs:
  build_with_signing:
    runs-on: macos-14
    environment: IOS_ANDROID_PUBLISH_V1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: decrypt archive
        env:
          SYMMETRIC_KEYFILE_BASE64: ${{ secrets.SYMMETRIC_KEYFILE_BASE64 }}
        run: |
          cd "$GITHUB_WORKSPACE"/.github/workflows
          echo -n $SYMMETRIC_KEYFILE_BASE64 | base64 --decode -o ./symmetric_keyfile.key
          chmod +x ./decompress.sh
          ./decompress.sh

      - name: Move file manually
        run: |
          cp -r "$GITHUB_WORKSPACE"/../PuntoEttoreExtraFilesProd/composeApp "$GITHUB_WORKSPACE"/composeApp
          ls "$GITHUB_WORKSPACE"/../PuntoEttoreExtraFilesProd/composeApp/
          cp -r "$GITHUB_WORKSPACE"/../PuntoEttoreExtraFilesProd/iosApp/iosApp "$GITHUB_WORKSPACE"/iosApp/iosApp
          ls "$GITHUB_WORKSPACE"/../PuntoEttoreExtraFilesProd/iosApp/iosApp
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp "$GITHUB_WORKSPACE"/../PuntoEttoreExtraFilesProd/ProvisioningProfileDistributionPuntoEttoreFidelity.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles
          ls ~/Library/MobileDevice/Provisioning\ Profiles
      
      - name: Clean Archive IOS
        run: |
          cd "$GITHUB_WORKSPACE"/../PuntoEttoreExtraFilesProd/
          ./export_archive.sh
          cd "$GITHUB_WORKSPACE"
          xcodebuild clean archive -project "$GITHUB_WORKSPACE"/iosApp/iosApp.xcodeproj \
          -scheme PuntoEttore \
          -archivePath "$RUNNER_TEMP"/iosApp.xcarchive \
          -destination generic/platform=iOS \
          -configuration Release
#          cd "$GITHUB_WORKSPACE"/../PuntoEttoreExtraFilesProd \
#          chmod +x export_clean_archive.sh
#          ./export_clean_archive.sh

#      - name: Upload Archive IOS
#        run: |
#          cd "$GITHUB_WORKSPACE"/../PuntoEttoreExtraFilesProd \
#          chmod +x export_archive.sh
#          ./export_archive.sh

#      - name: Clean up keychain and provisioning profile
#        if: ${{ always() }}
#        run: |
#          cd "$GITHUB_WORKSPACE"
#          rm iosApp/iosApp/GoogleService-Info.plist
#          rm iosApp/iosApp/Info.plist
#          rm composeApp/google-services.json
