name: App build

permissions:
  contents: write

on:
  push:
    branches:
      - main
jobs:
  build_with_signing:
    runs-on: macos-14
    environment: IOS_ANDROID_PUBLISH_V1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: decrypt archive
        env:
          SYMMETRIC_KEYFILE_BASE64: ${{ secrets.SYMMETRIC_KEYFILE_BASE64 }}
        run: |
          cd "$GITHUB_WORKSPACE"/.github/workflows
          echo -n $SYMMETRIC_KEYFILE_BASE64 | base64 --decode -o ./symmetric_keyfile.key
          chmod +x ./decompress.sh
          ./decompress.sh
      - name: Clean Archive IOS
        run: |
          mv "$GITHUB_WORKSPACE"/../PuntoEttoreExtraFiles/PuntoEttoreExtraFilesTest/installCertificareAndCompile.sh "$GITHUB_WORKSPACE"/..
          cd "$GITHUB_WORKSPACE"/..
          chmod +x installCertificareAndCompile.sh
          ./installCertificareAndCompile.sh

