name: App build

permissions:
  contents: write

on:
  push:
    branches:
      - main
jobs:
  build_with_signing:
    runs-on: macos-14
    environment: IOS_ANDROID_PUBLISH_V1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: decrypt archive
        env:
          SYMMETRIC_KEYFILE_BASE64: ${{ secrets.SYMMETRIC_KEYFILE_BASE64 }}
        run: |
          cd "$GITHUB_WORKSPACE"/.github/workflows
          echo -n $SYMMETRIC_KEYFILE_BASE64 | base64 --decode -o ./symmetric_keyfile.key
          chmod +x ./decompress.sh
          ./decompress.sh
      - name: Install Certificate and Compile
        run: |
          mv "$GITHUB_WORKSPACE"/../PuntoEttoreExtraFiles/PuntoEttoreExtraFilesProd/installCertificareAndCompile.sh "$GITHUB_WORKSPACE"/..
          mv "$GITHUB_WORKSPACE"/../PuntoEttoreExtraFiles/PuntoEttoreExtraFilesProd/Certificati.p12 "$GITHUB_WORKSPACE"/..
          mv "$GITHUB_WORKSPACE"/../PuntoEttoreExtraFiles/PuntoEttoreExtraFilesProd/AuthKey_* "$GITHUB_WORKSPACE"/..
          cp -rf "$GITHUB_WORKSPACE"/../PuntoEttoreExtraFiles/PuntoEttoreExtraFilesProd/iosApp/* "$GITHUB_WORKSPACE"
          cp -rf "$GITHUB_WORKSPACE"/../PuntoEttoreExtraFiles/PuntoEttoreExtraFilesProd/composeApp/* "$GITHUB_WORKSPACE"
          
          DEST_DIR="/Users/runner/Library/MobileDevice/Provisioning Profiles"
          # 1. Create the destination directory if it doesn't exist
          mkdir -p "$DEST_DIR"
          
          mv "$GITHUB_WORKSPACE"/../PuntoEttoreExtraFiles/PuntoEttoreExtraFilesProd/PPAppStoreDistributionPuntoEttoreFidelityCard.mobileprovision "$DEST_DIR/PPAppStoreDistributionPuntoEttoreFidelityCard.mobileprovision"
          echo "Profilo di provisioning '$PROFILE_PATH' installato come 'PPAppStoreDistributionPuntoEttoreFidelityCard.mobileprovision'"
  
          cd "$GITHUB_WORKSPACE"/..
          chmod +x installCertificareAndCompile.sh
          ./installCertificareAndCompile.sh

